all: rush-02

rush-02:
	gcc -Wall -Werror -Wextra -o rush-02 main.c ft_get_dict.c ft_check_arg.c ft_str_is_numeric.c ft_strcpy.c ft_strstr.c ft_put_error.c ft_put_dict_error.c ft_str_is_printable.c ft_putstr.c ft_len.c

run:
	./rush-02

fclean:
	rm -f rush-02

re:
	fclean all
